AWSTemplateFormatVersion: '2010-09-09'
Description: Create an S3 bucket using CloudFormation

Resources:
  RuhailS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: ruhail-cloudformation-demo
      AccessControl: Private
